# Generated by Django 3.2.18 on 2023-04-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='registration_date',
            new_name='created_date',
        ),
    ]
